create sequence hibernate_sequence start with 1 increment by 1;
create table doctors
(
    id         bigint generated by default as identity,
    created_at timestamp not null,
    updated_at timestamp not null,
    name       varchar(255),
    version    int,
    primary key (id)
);

create table opentimes
(
    id         bigint generated by default as identity,
    created_at timestamp not null,
    updated_at timestamp not null,
    open_date  timestamp not null,
    start_Time timestamp not null,
    end_Time   timestamp not null,
    doctor_id  bigint    not null,
    version    int,
    primary key (id),
    FOREIGN KEY (doctor_id) REFERENCES doctors (id)
);

create table opentimeslots
(
    id                     bigint generated by default as identity,
    created_at             timestamp not null,
    updated_at             timestamp not null,
    open_time_appointment  timestamp not null,
    open_time_id           bigint    not null,
    patient_appointment_id bigint,
    version                int,
    primary key (id),
    FOREIGN KEY (open_time_id) REFERENCES opentimes (id)
);


create table patientappointments
(
    id                bigint generated by default as identity,
    created_at        timestamp not null,
    updated_at        timestamp not null,
    patient_name      varchar(255),
    phone_number      varchar(255) unique,
    version           int,
    open_time_slot_id bigint    not null,
    primary key (id),
    FOREIGN KEY (open_time_slot_id) REFERENCES opentimeslots (id)
);

alter table opentimeslots
    add constraint FKiipp3aj4qviuer9lnvl1q713b foreign key (patient_appointment_id) references patientappointments;

insert into doctors
values (1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'John', 0);
commit;